### ISSUE TITLE
materialToolStripMenuItem can't add item to DropDownItems

### ISSUE THREAD

**Issue by idea-zone** [bubuntoid/MaterialSkin.NET5#3]
materialToolStripMenuItem can't add item to DropDownItems, it's show bad and throw ERROR on Running.

I am is here: 
.NET 5.0.403;
VS2019 16.11.7;
MaterialSkin.NET5 1.0.1;

Here is DesignMode:
![Design Mode](https://user-images.githubusercontent.com/53116704/211518344-6f8834de-9875-493d-82eb-3cbc4a81c50f.png)

~~~text
   Exception:  System.NullReferenceException;
   Error Message: Object reference not set to an instance of an object;
   HResult:   -2147467261;
   StackTrace: 
   at System.Windows.Forms.Layout.CommonProperties.xClearPreferredSizeCache(IArrangedElement element)
   at System.Windows.Forms.ToolStripDropDown.OnOwnerItemFontChanged(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnFontChanged(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnFontChanged(EventArgs e)
   at System.Windows.Forms.ToolStripItem.OnOwnerFontChanged(EventArgs e)
   at System.Windows.Forms.ToolStrip.OnFontChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Font(Font value)
   at System.Windows.Forms.ToolStrip.set_Font(Font value)
   at MaterialSkin.Controls.MaterialMenuStrip.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at MaterialSkin.Controls.MaterialForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
~~~

**Comment by bubuntoid** [comment]
Hello @idea-zone
I fixed up rendering issue, but didn`t get any exception that you described. Could you share your form sources somewhere?

![image](https://user-images.githubusercontent.com/51204805/211727646-58e697b7-c25a-4a58-8702-598ad04aee22.png)
![image](https://user-images.githubusercontent.com/51204805/211727715-2a80d64d-b07a-49bd-bf18-3c31ee4a3a29.png)

**Comment by bubuntoid** [comment]
1.0.2 released https://www.nuget.org/packages/MaterialSkin.NET5/

**Comment by idea-zone** [comment]
Thank you for your work！Here is my Test Project:  [TestMterial.NET5.zip](https://github.com/bubuntoid/MaterialSkin.NET5/files/10391206/TestMterial.NET5.zip). My Develop's OS is Winodws 10.

###### Running Info
![RunningInfo](https://user-images.githubusercontent.com/53116704/211781748-9a1d1686-221c-46a4-8aa1-78b9ed3fc160.png)

###### all dotnet version on my computer
![image](https://user-images.githubusercontent.com/53116704/211782224-3146fe9f-6013-4af2-a3e4-7755db3e016c.png)

**Comment by bubuntoid** [comment]
@idea-zone I suppose you edited Form1.Designer by yourself.

![image](https://user-images.githubusercontent.com/51204805/211790038-fc1faee7-650a-467c-b477-a2a0de0ab261.png)
P.S. left code block is from your sources and right is exceptionless fix


I suggest you to recreate MaterialMenuStrip control with using just VS form editor

**Comment by idea-zone** [comment]
I do it with just VS form editor. But I use the red-marked item:

![image](https://user-images.githubusercontent.com/53116704/211814801-4362d73f-2bac-4552-82db-cdd9cba66801.png)

I find it when I use "MaterialToolStripMenuItem" ,it cannot has "MaterialToolStripMenuItem" as DropDownItems , but when I use "MenuItem", it's work .

**But  there is one rendering issue  when I use MenuItem as top-item and MaterialToolStripMenuItem as DropDownItems** : 

![image](https://user-images.githubusercontent.com/53116704/211815805-2d4d88ec-1ead-41e1-bf64-dbf3e42842d4.png)

Thanks very much for you help.

**Comment by bubuntoid** [comment]
You should use only default **System.Windows.Forms.ToolStripMenuItem**.

Is there any reason to use **MaterialToolStripMenuItem** in your project?
